### ISSUE TITLE
White screen appears in between scheduled presentations.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#140]
When two or more presentations are in a schedule, a white screen flashes between the scheduled presentations. White screen lasts ~1 second, and appears no matter what kind of content is scheduled.

You can replicate this issue by adding this schedule to your display https://goo.gl/RACWtj

What should happen?
Transitions between presentations within the schedule should be seamless. 

Player Version: RisePlayerElectron 2016.10.05.15.59
Viewer Version: 2-00-201610041830
OS Tested: Windows 10 64bit, Ubuntu 14.04 64bit

**Comment by alex-deaconu** [comment]
@btfrise taking a look at the content, all 3 Presentations' Placeholders have the `Fade` transition selected. To clarify, when `Fade` is selected this is expected behaviour. I've double checked with the previous Viewer version (http://r12-dot-rvashow2.appspot.com/) and I believe the "white screen" effect also occurs there (ie. this is a pre-existing issue). Thanks.

**Comment by btfrise** [comment]
Confirmed, thanks @alex-deaconu I'll close.

**Comment by alex-deaconu** [comment]
@btfrise thanks!
