### ISSUE TITLE
When you play a Weather Widget that is set to use "Display Address" and you have a Display Address set, nothing shows in the Placeholder

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/viewer#67]
<b>How it works now:</b>
1. Add any Weather Widget to a Presentation, and set it to use Display Address. Confirm that the Display has a set Display Address in the RVA.
2. Play on a Display, and notice that nothing shows in the Weather Placeholder.

Regardless of which Weather Widget you use, this always happens, and I recall when this was discussed before that it was determined this is a viewer bug.

This video shows the issue in action: https://goo.gl/i7TWZN

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ka7Z7rqw&#x2F;879-issue-67-viewer-not-returning-display-address"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue #67 Viewer not returning Display Address</a>

**Comment by alex-deaconu** [comment]
@robb-price I'm currently investigating this issue, which is quite old.

From what I can tell, the Weather Widget (DigiChief) is requesting the Address correctly. Also, the Viewer doesn't have any issues providing the Address to the Widget.

However, from my investigation, the following behaviour is occurring:
1. If the Display address is blank, a blank address is returned; same probably goes for the Company address. I would imagine this is normal behaviour.
2. If the Display address is updated, a new update is sent to the Viewer; however since the Content hasn't changed, the Presentation will not refresh.
3. If the Display's Use Company Address is checked on/off, a new update is sent to the Viewer; however as in case 2, the Presentation will not refresh.
4. If the Display's Use Company Address is checked, and the Company Address is updated, the Viewer does not receive a new update (unlike scenarios 2, 3).

I guess the easiest solution for correcting scenarios 2, 3, 4 is re-saving the content or restarting the Display.

While the above behaviour does indicate a flaw in logic for the Viewer/Core, it does not correspond with the Issue description. So, either this issue was somehow inadvertently fixed, or while validating it one or a combination of these scenarios was encountered.

To conclude. 
Since I cannot replicate the issue as described, would it be possible for you or a CS teammate to try to replicate?
Also, can you take a look at the above scenarios and let me know if these are indeed things we need to fix or can live without?

@ByronDarlison @ezequielc FYI. Thoughts?

Thanks!

**Comment by robb-price** [comment]
@alanclayton @ByronDarlison @ezequielc We will test again after Chrome 50 testing and let you know if we can recreate.

**Comment by robb-price** [comment]
@alex-deaconu @ByronDarlison @ezequielc I retested this using the Digichief Weather Widget, and it works as expected, so I think this has been inadvertently fixed.

We can live without Scenario's 1 - 4, as a quick save of the Presentation rectifies 2 - 4, and we haven't had a single person bring scenario 1 to our attention.

This issue can be closed.

**Comment by alex-deaconu** [comment]
Thanks @robb-price !
